---
- name: Install python venv command
  ansible.builtin.package:
    name: "{{ python3_pkg[ansible_facts['distribution'] + ansible_facts['distribution_major_version']] }}"
    # it depends:
    # OS        package       command           python_ver
    # ubuntu22  python3-venv  python3           3.10.12
    # ubuntu24  python3-venv  python3           3.12.3
    # RL8       python39      python3.9         3.9.19
    # RL9       python3       python3,python3.9 3.9.18
  vars:
    python3_pkg:
      Rocky8: python39
      Rocky9: python3
      Ubuntu22: python3-venv
      Ubuntu24: python3-venv

- name: Install dependencies into virtualenv
  ansible.builtin.pip:
    name: "{{ ansible_init_pip_packages }}"
    state: present
    virtualenv: /usr/lib/ansible-init
    virtualenv_command: "{{ python3_cmds[ansible_facts['distribution']] }} -m venv --upgrade-deps"
  vars:
    python3_cmds:
      Ubuntu: python3
      Rocky: python3.9

- name: Ensure ansible-init ansible_home directory permissions allow everyone to execute
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_init_ansible_home_directory }}"
    mode: "0755"

- name: Ensure config directories exist
  ansible.builtin.file:
    state: directory
    path: "/etc/ansible-init/{{ item }}"
    mode: "0755"
  loop:
    - vars
    - playbooks
    - includes
    - inventory

- name: Install Ansible config file
  ansible.builtin.template:
    src: ansible.cfg.j2
    dest: /etc/ansible-init/ansible.cfg
    mode: "0644"

- name: Install ansible-init script
  ansible.builtin.copy:
    src: ansible-init.py
    dest: /usr/bin/ansible-init
    mode: "0755"

- name: Install systemd unit file
  ansible.builtin.copy:
    src: ansible-init.service
    dest: /etc/systemd/system/ansible-init.service
    mode: "0644"

- name: Ensure ansible-init service is enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: ansible-init.service
    enabled: true
