---
ansible_init_pip_packages:
  - ansible
  - jmespath
  - requests

# Ansible home directory for ansible-init
# https://docs.ansible.com/projects/ansible/latest/reference_appendices/config.html#ansible-home
ansible_init_ansible_home_directory: "/var/lib/ansible-init"

# Multiline string of default config to add to
# ansible.cfg
ansible_init_ansible_cfg_default_extra:

# Multiline string of extra config to add to
# ansible.cfg
ansible_init_ansible_cfg_extra:
