---
name: Build and test PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

'on':
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

jobs:
  lint:
    permissions:
      contents: read
      # To report GitHub Actions status checks
      statuses: write
    uses: ./.github/workflows/lint.yml
